apiVersion: v1
kind: ConfigMap
metadata:
  name: neurodrug-config
  namespace: neurodrug
data:
  POSTGRES_HOST: "postgres-service"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "neurodrug"
  REDIS_URL: "redis://redis-service:6379/0"
  CELERY_BROKER_URL: "redis://redis-service:6379/1"
  CELERY_RESULT_BACKEND: "redis://redis-service:6379/2"
  MLFLOW_TRACKING_URI: "http://mlflow-service:5000"
  ENVIRONMENT: "production"
